<h3><?php echo $this->translate('Роли');?></h3>
<button class="i_plus icon fr"><?php echo $this->translate('Добавить');?></button><br />

<div class="clear"></div><br />

<table cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th>№</th>
            <th><?php echo $this->translate('Название');?></th>
            <th><?php echo $this->translate('Описание');?></th>
            <th><?php echo $this->translate('Редактировать');?></th>
            <th><?php echo $this->translate('Удалить');?></th>
        </tr>
    </thead>
    <tbody>
<?php if($this->roles) { ?>
          <?php $i = 0; foreach($this->roles as $role) { $i++;?>
                <tr>
                    <td><?php echo $i; ?></td>
                    <td><?php echo $role->getName(); ?></td>
                    <td><?php echo $role->getDescription(); ?></td>            
                    <td><a href="<?php $id = $role->getId();
echo $this->url(array('module'=>'dashboard','controller'=>'role','action'=>'update','id' => $id ), null, FALSE);	
?>"><img src="/../images/edit.png"  height="16" width="16"/></a></td>
 <td><a data-id ="<?php
echo $id;	
?>" class="delete" ><img src="/../images/delete.png"  height="16" width="16"/></a></td>
                </tr>
            <?php } ?>
        <?php } else { ?>
        <?php } ?>
    </tbody>
</table>